// This file is automatically generated by AWS Amplify. It will be overwritten on deploy.
// To run Monarch locally, replace the first 5 values with their corresponding environment variable.
const awsmobile = {
    "aws_project_region": "AWS_REGION",
    "aws_cognito_region": "AWS_REGION",
    "aws_user_pools_id": "COGNITO_USER_POOL_ID",
    "aws_cognito_identity_pool_id": "COGNITO_IDENTITY_POOL_ID",
    "aws_user_pools_web_client_id": "COGNITO_CLIENT_ID",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};
export default awsmobile;