// This file is automatically generated by AWS Amplify. It will be overwritten on deploy.
// To run Monarch locally, replace the first 5 values with their corresponding environment variable.
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jlRWv5ExI",
    "aws_cognito_identity_pool_id": "us-east-2:bf437025-d7bb-4691-9217-6dfe652cde4d",
    "aws_user_pools_web_client_id": "6346nfustdjk5fdlc7gspqscq3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};
export default awsmobile;