export const SITES = [
  {
    "Asset Name": "Jackson Mann K-8/Horace Mann School",
    "Status": "Built",
    "Neighborhood": "Allston",
    "Address": "40 Armington St",
    "Asset Type": "Bioretention area, vegetated swale, overflow/outlet, curb inlet, trench drain, forebay",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BWSC, BPS",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit",
    "Link to Maintenance Checklist": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "https://drive.google.com/file/d/1ERcPH2MCtmLonHHcvswEpLpPjagmn6yj/view?usp=sharing",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Brighton Ave and Harvard Ave Medians",
    "Status": "Built",
    "Neighborhood": "Allston",
    "Address": "Intersection of Brighton Ave and Harvard Ave",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1vecFidU9K0ZbJuF4untD-Fhs5Dbveveb/view?usp=sharing",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Allston/Brighton",
    "Address": "224 Western Ave ",
    "Asset Type": "Tree pit/planter (2 recorded in this location) , owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Allston/Brighton",
    "Address": "0 Guest St",
    "Asset Type": "Tree pit/planter (2 recorded in this location), rain garden, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Allston/Brighton",
    "Address": "0 Life St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Boston Public Library - Central Branch",
    "Status": "Built",
    "Neighborhood": "Back Bay",
    "Address": "0 Boylston St/Exeter St ",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPL",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "BAC Green Alley",
    "Status": "Built",
    "Neighborhood": "Back Bay ",
    "Address": "Public Alley 444",
    "Asset Type": "Porous asphalt",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Public Alley #543",
    "Status": "Built",
    "Neighborhood": "Back Bay ",
    "Address": "Public Alley #543",
    "Asset Type": "Porous Asphalt, catch basin inlet",
    "Description": "",
    "PIC no.": "n/a",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Hemenway St. (#52&#103) ",
    "Status": "Built",
    "Neighborhood": "Back Bay ",
    "Address": "52 & 103 Hemenway St",
    "Asset Type": "Tree Pit Infiltration Systems, catch basin inlet",
    "Description": "",
    "PIC no.": "n/a",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Back Bay/Beacon Hill",
    "Address": "30 Dalton St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Back Bay/Beacon Hill",
    "Address": "699 Boylston St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Boston Medical Center",
    "Address": "0 Albany St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Cassidy Playground",
    "Status": "Built",
    "Neighborhood": "Brighton",
    "Address": "379 Chestnut Hill Ave",
    "Asset Type": "Comprehensive park renovation, bioretention area, overflow/outlet, perforated pipe, gravel filter",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/drive/folders/1qLcIFrvbA4-UXyAR6IdU2vG2nHG42uqB?usp=sharing",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/document/d/1qvrv23EpjgvjIiX-9lhPuqbbeloU1qAe/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://drive.google.com/file/d/1XzHZDs1iQvlqCbU8Rl_t5PWP93cOQxGg/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Central",
    "Address": "20 Somerset St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Central",
    "Address": "45 Hudson St/Kneeland St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Liberty Tree Plaza",
    "Status": "Built",
    "Neighborhood": "Chinatown",
    "Address": "2 Boylston Street",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1msLLrk1mLPWueG3vh9wBP5e8oQm_ru-t/view?usp=sharing",
    "Link to Maintenance Checklist": "https://drive.google.com/file/d/1ovkdAYsN1a1m_VD_Cd-8__7rPjbWpceO/view?usp=sharing",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Beach St. ",
    "Status": "Built",
    "Neighborhood": "Chinatown ",
    "Address": "",
    "Asset Type": "Permeable Pavers, Tree plantings, Treeways, catch basin inlet",
    "Description": "",
    "PIC no.": "2018.0005",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Downer Avenue Park",
    "Status": "Built",
    "Neighborhood": "Dorchester",
    "Address": "40 Downer Avenue",
    "Asset Type": "Comprehensive park renovation",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "McConnell Playground",
    "Status": "Built",
    "Neighborhood": "Dorchester",
    "Address": "30 Denny St",
    "Asset Type": "Comprehensive park renovation",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Harambee Park",
    "Status": "Built",
    "Neighborhood": "Dorchester",
    "Address": "930 Blue Hill Avenue",
    "Asset Type": "Comprehensive park renovation, permeable pavers, stormwater chambers, perforated pipe, drywell, retention pond",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/document/d/1qvrv23EpjgvjIiX-9lhPuqbbeloU1qAe/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Peabody Square",
    "Status": "Built",
    "Neighborhood": "Dorchester",
    "Address": "Dorchester Ave/Ashmont St/Talbot Ave",
    "Asset Type": "Permeable pavers, rain garden, overflow/outlet",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1n_PqLXECAg6O_AqHVIVPyDS5GRoQbID3/view?usp=sharing",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/document/d/1qvrv23EpjgvjIiX-9lhPuqbbeloU1qAe/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://drive.google.com/file/d/1XzHZDs1iQvlqCbU8Rl_t5PWP93cOQxGg/view?usp=sharing\nhttps://drive.google.com/file/d/1aWVVyctpusxa_GbaPQTFdAaXiI-HVSSk/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Codman Square ",
    "Status": "Built",
    "Neighborhood": "Dorchester",
    "Address": "Washington St/Norfolk/Talbot/Epping ",
    "Asset Type": "Plantings/bioretention rain gardens, storm water trenching, porous asphalt, overflow/outlet, perforated pipe, gravel filter, catch basin inlet, curb inlet, trench drain, splash pad",
    "Description": "",
    "PIC no.": "2021.0006",
    "Partner Depts.": "BWSC, PWD, BTD",
    "Maintenance Agreement?": "Yes ",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1x5gCnntqNWoAjoZvqac8L5VBsNBwuRfP/view?usp=sharing",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1XL24uw7zrk9eca3lgaqIjRhP9sQ5YT_D/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/spreadsheets/d/1L3N6g13b9wN5DXtcFsw-HEMRweCBLAX6/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Upham's Corner ",
    "Status": "Built",
    "Neighborhood": "Dorchester",
    "Address": "Columbia Rd. & Dudly St. ",
    "Asset Type": "Plantings/Gardens, catch basin inlet, enhanced tree trench",
    "Description": "",
    "PIC no.": "2013.0046",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "Yes ",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1X3C4QzRQ9pLw__KbGKaUXdWIxbq1zCyv/view?usp=sharing",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "New England Ave ",
    "Status": "Built",
    "Neighborhood": "Dorchester ",
    "Address": "Southern Ave. to Mallard Ave.",
    "Asset Type": "Plantings/Gardens, bioretention swales, storm water trenching, rain garden, overflow/outlet, perforated pipe, splash pad, enhanced tree trench, tree pit",
    "Description": "",
    "PIC no.": "2019.0013",
    "Partner Depts.": "BWSC, PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/14ljkrGy3AaB6Y9o--Fe_TJzVje6T_NR6/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/spreadsheets/d/1afskMALH1Fs0ghk-97K9aiv0ofBbFmiv/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://drive.google.com/file/d/1aWVVyctpusxa_GbaPQTFdAaXiI-HVSSk/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": "Yes"
  },
  {
    "Asset Name": "Quincy St. ",
    "Status": "Built",
    "Neighborhood": "Dorchester ",
    "Address": "Columbia Rd to Blue Hill Ave",
    "Asset Type": "Tree Planting, porous concrete slabs, catch basin inlet",
    "Description": "",
    "PIC no.": "2017.0064",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "https://drive.google.com/file/d/1aWVVyctpusxa_GbaPQTFdAaXiI-HVSSk/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "City Hall Plaza",
    "Status": "Built",
    "Neighborhood": "Downtown",
    "Address": "1 City Hall Square",
    "Asset Type": "Porous pavers, porous \"asphalt,\" tree infiltration trenches, trench drains",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Government Center T Station",
    "Status": "Built",
    "Neighborhood": "Downtown",
    "Address": "1 City Hall Square",
    "Asset Type": "Porous pavers, tree infiltration trenches, trench drains",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Emerson College ",
    "Status": "Built",
    "Neighborhood": "Downtown",
    "Address": "110 Boylston St",
    "Asset Type": "Rain garden",
    "Description": "",
    "PIC no.": "2018.0070",
    "Partner Depts.": "",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Maybe",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Elliot Norton Park",
    "Status": "Built",
    "Neighborhood": "Downtown",
    "Address": "295 Tremont St",
    "Asset Type": "Rain garden, perforated pipe, drywell, catch basin inlet, trench drain",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/document/d/1qvrv23EpjgvjIiX-9lhPuqbbeloU1qAe/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://drive.google.com/file/d/1XzHZDs1iQvlqCbU8Rl_t5PWP93cOQxGg/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Boylston St. ",
    "Status": "Built",
    "Neighborhood": "Downtown ",
    "Address": "76 - 162 Boylston St",
    "Asset Type": "Permeable Pavers, Plantings, permeable base layering, catch basin inlet, tree pit",
    "Description": "",
    "PIC no.": "2021.0053",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1kBW66DYcVSJxbACQxQUP-nkbsGu6TCET/view?usp=sharing",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1_2bFDl5V0M-57BbK7Hyc54ChbDQaSeLG/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Noyes Playground",
    "Status": "Built",
    "Neighborhood": "East Boston",
    "Address": "86 Boardman St",
    "Asset Type": "Comprehensive park renovation, cleanouts, rain garden, overflow/outlet, perforated pipe, catch basin inlet",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "https://drive.google.com/file/d/1XzHZDs1iQvlqCbU8Rl_t5PWP93cOQxGg/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Central Square",
    "Status": "Built",
    "Neighborhood": "East Boston",
    "Address": "Harvard St/School St. ",
    "Asset Type": "Porous pavers, storm water trench, control drain man holes, porous asphalt, permeable concrete slabs, cleanouts, catch basin inlets, enhanced tree trench",
    "Description": "",
    "PIC no.": "2013.0045",
    "Partner Depts.": "BWSC, PWD, BTD, BPRD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://drive.google.com/file/d/1EMBhAV0o2R0qEVeBs7RsFhD0BeS3hVgD/view?usp=sharing\nhttps://drive.google.com/file/d/1y4dKBGbiFPhqKs1rglmV5j01H_7zKL9H/view?usp=sharing\nhttps://drive.google.com/file/d/1DrLpBAKDJqyxsInPw68GUd13QdeYcc6g/view?usp=sharing\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true ",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1djMm-E4d56wh_fqTcI-neooR4W1zRRYR/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "https://drive.google.com/file/d/18IC0VBAj02_cNFou2dfzWYyTLwX6f-BI/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "East Boston Greenway Rain Garden",
    "Status": "Built",
    "Neighborhood": "East Boston",
    "Address": "Gove Street (north of the Greenway entrance)",
    "Asset Type": "Rain garden",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/document/d/1qvrv23EpjgvjIiX-9lhPuqbbeloU1qAe/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://drive.google.com/file/d/1XzHZDs1iQvlqCbU8Rl_t5PWP93cOQxGg/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Fenway Multiuse Path",
    "Status": "Built",
    "Neighborhood": "Fenway",
    "Address": "Maitland Street (Opposite David Ortiz Way)",
    "Asset Type": "Bioswale",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BTD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1xdKI_9UU8Siu88Y2JPkiVHE3OxTZehqY/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Audubon Circle ",
    "Status": "Built",
    "Neighborhood": "Fenway",
    "Address": "Park St./Beacon St. ",
    "Asset Type": "Rain Garden, permeable pavers, overflow/outlet, catch basin inlet, enhanced tree trench",
    "Description": "",
    "PIC no.": "2015.0041",
    "Partner Depts.": "BWSC, PWD, BTD",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/19Dg-XhJSgHF_LGrLK4nehfevzPm48PjQ/view?usp=sharing",
    "Link to Maintenance Checklist": "https://drive.google.com/file/d/17hXaxynxzyjBDw9vEzVwm2Ai20F_khhe/view?usp=sharing\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1erIeg8r7Y7BZVeHrERhUf8yV8Hl7eIi8/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "https://drive.google.com/file/d/1VOQoMwxLbJOraFwGQKv_oGKdfiQAz2Za/view?usp=sharing",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Fenway/Kenmore",
    "Address": "45 Francis St",
    "Asset Type": "Tree pit/planter (2 recorded in this location), owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Fenway/Kenmore",
    "Address": "1282 Boylston St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Fenway/Kenmore",
    "Address": "132 Brookline Ave",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Fenway/Kenmore",
    "Address": "888 Boylston St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Summer St. ",
    "Status": "Built",
    "Neighborhood": "Fort Point",
    "Address": "",
    "Asset Type": "Plantings, permeable pavers, catch basin inlet",
    "Description": "",
    "PIC no.": "2017.0011",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "CIP 17-32 South & Bussey ",
    "Status": "Built",
    "Neighborhood": "Jamacia Plain",
    "Address": "South St & Bussey St",
    "Asset Type": "Rain Garden, overflow/outlet, catch basin inlet, splash pad",
    "Description": "",
    "PIC no.": "2017.0056",
    "Partner Depts.": "BWSC, BPS",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://drive.google.com/file/d/1-6CMcFYx7X_Dj4quJG9IURBhw7qKTfB4/view?usp=sharing",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/16fmf1Q6kyKefu2WygJHMNS3RdSzP_pfp/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Jamaica Plain",
    "Address": "105A South Huntington Ave",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Everett St. ",
    "Status": "Built",
    "Neighborhood": "Jeffries Point ",
    "Address": "",
    "Asset Type": "Permeable Pavers, drywell, catch basin inlet, tree pit",
    "Description": "",
    "PIC no.": "2015.0038",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Maybe",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Edward M. Kennedy Academy for Health Careers",
    "Status": "Built",
    "Neighborhood": "Mission Hill",
    "Address": "10 Fenwood Rd",
    "Asset Type": "Porous asphalt, stormwater planter, catch basin inlet, splash pad, enhanced tree trench",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BWSC, BPS",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit",
    "Link to Maintenance Checklist": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1UISGTklH_Um72tY37TEjQyNKShATn7XV/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "https://drive.google.com/file/d/1DtpIBBmLSVfG7O-TuI5uyb4jF2p8DCdD/view?usp=sharing",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "North Dorchester",
    "Address": "540-545 Columbia Rd",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Rachel Revere Square",
    "Status": "Built",
    "Neighborhood": "North End",
    "Address": "98 North Square",
    "Asset Type": "Comprehensive park renovation - Porous paving, tree infiltration trenches",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/drive/folders/1qLcIFrvbA4-UXyAR6IdU2vG2nHG42uqB?usp=sharing",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/document/d/1qvrv23EpjgvjIiX-9lhPuqbbeloU1qAe/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://drive.google.com/file/d/1XzHZDs1iQvlqCbU8Rl_t5PWP93cOQxGg/view?usp=sharing",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Langone and Puopolo Parks",
    "Status": "Built",
    "Neighborhood": "North End",
    "Address": "529 Commercial St",
    "Asset Type": "Comprehensive park renovation, drywell",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BPRD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Washington Irving Middle School",
    "Status": "Built",
    "Neighborhood": "Roslindale",
    "Address": "105 Cummins Hwy",
    "Asset Type": "Bioretention area, bioswale, overflow/outlet, stormwater chambers, subsurface gravel filter, catch basin inlet, trench drain, splash pad, forebay, enhanced tree pit",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BWSC, BPS",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit",
    "Link to Maintenance Checklist": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1JuYG_SG59k5jkglOCZEivvbkO1XIrWXw/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "https://drive.google.com/file/d/13NuBSuNY2qZDgheAPcQdyGxYOf83W7ML/view?usp=sharing",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Rafael Hernandez K-8 School",
    "Status": "Built",
    "Neighborhood": "Roxbury",
    "Address": "61 School St",
    "Asset Type": "Bioretention area, overflow/outlet, stormwater chambers, perforated pipe, drywell, subsurface gravel filter, catch basin inlet, forebay",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BWSC, BPS",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit",
    "Link to Maintenance Checklist": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "https://drive.google.com/file/d/1cCRoTW9yCmw-eRPo7hDxuUYPxNi2Lj5v/view?usp=sharing",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "David A. Ellis Elementary School",
    "Status": "Built",
    "Neighborhood": "Roxbury",
    "Address": "302 Walnut Ave",
    "Asset Type": "Permeable pavers, cleanouts, rain garden, overflow/outlet, basin inlet forebay, enhanced tree trench",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BWSC, BPS",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit",
    "Link to Maintenance Checklist": "https://docs.google.com/document/d/1L_08k3e7P4NiMW4y8KuWL_0lG6_xPXjL/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true\nhttps://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Harrison Ave ",
    "Status": "Built",
    "Neighborhood": "Roxbury",
    "Address": "Melnea Cass Blvd. to East Lenox St.",
    "Asset Type": "Porous Pavers and Tree plantings, perforated pipe, drywell, catch basin inlet, enhanced tree trench",
    "Description": "",
    "PIC no.": "n/a",
    "Partner Depts.": "BWSC, PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1AQ6H84jzzTZ61U6QSuXDhQ8vfZl-LWKw/view?usp=sharing,\nhttps://drive.google.com/file/d/1jvb6ILWVDt8-9xjLyUTYoiVmaEFwxpls/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "https://docs.google.com/spreadsheets/d/13r9BGd-IHBvz6G1f_YLUyjCrGH3WIb_L/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "Roxbury",
    "Address": "0 Fenwood Rd",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Ruggles Street Municipal Lot",
    "Status": "Built",
    "Neighborhood": "Roxbury",
    "Address": "30 Ruggles St Municipal Lot",
    "Asset Type": "Tree pit/planter, rain garden, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "BTD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Nubian Sq. Phase 1",
    "Status": "Built",
    "Neighborhood": "Roxbury ",
    "Address": "149 Dudley Street",
    "Asset Type": "Pavers, Planters, stormwater trench, Porous asphalt, Anti-seep collars ",
    "Description": "",
    "PIC no.": "2018.0103",
    "Partner Depts.": "",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South Boston",
    "Address": "0 Sleeper St/Northern Ave/Seaport BLVD",
    "Asset Type": "Tree pit/planter",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South Boston",
    "Address": "0 Seaport Blvd",
    "Asset Type": "Tree pit/planter (2 recorded in this location), owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South Boston",
    "Address": "4,6 Leo M. Birmingham Parkway",
    "Asset Type": "Tree pit/planter (2 recorded in this location), owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South Boston",
    "Address": "0 Anchor St/Bullock St/ D St/ Danby St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South Boston",
    "Address": "411 D Street",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South End",
    "Address": "0 East Concord St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "DUPLICATE? Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South End",
    "Address": "0 Harrison Ave/ Herald St/ Traveler St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Tree pit/planter",
    "Status": "Built",
    "Neighborhood": "South End",
    "Address": "275 Albany St",
    "Asset Type": "Tree pit/planter, owner PUBLIC, maintenance PUBLIC",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Albany St. (#443 &500)",
    "Status": "Built",
    "Neighborhood": "South End ",
    "Address": "443 & 500 Albany St",
    "Asset Type": "Tree Pit Infiltration Systems, catch basin inlet",
    "Description": "",
    "PIC no.": "n/a",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Connect Historic Boston Bike Trail ",
    "Status": "Built",
    "Neighborhood": "West End",
    "Address": "78 Staniford Street",
    "Asset Type": "Porous Pavers, Plantings, porous asphalt, rain garden, overflow/outlet, drywell, catch basin inlet",
    "Description": "",
    "PIC no.": "2014.0024",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "https://docs.google.com/spreadsheets/d/1zltfBNVfASjwYW4pP4h4XChb5obZ4Bgq/edit?usp=sharing&ouid=108459017931706771025&rtpof=true&sd=true",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "--------------------",
    "Status": "",
    "Neighborhood": "",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Coolidge Road",
    "Status": "Not Built",
    "Neighborhood": "Allston",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Daisy Field",
    "Status": "Not Built",
    "Neighborhood": "Jamaica Plain",
    "Address": "",
    "Asset Type": "",
    "Description": "BWSC is treating a 70-acre catchment area with a subsurface gravel feature. It is an Olmstead park that P&R is planning to completely redo. It was going to be used as a Muddy River staging ground, but no longer. There is middle- and high-density residential in the catchment area above. The water is relatively phosphorus-polluted.",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Ave Louis Pasteur ",
    "Status": "Not Built",
    "Neighborhood": "Longwood",
    "Address": "",
    "Asset Type": "Rain Garden ",
    "Description": "",
    "PIC no.": "2021.0029",
    "Partner Depts.": "",
    "Maintenance Agreement?": "Pending",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1oaBoEfJcpX2X5ClukH9kjgflX4oDxNo0/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Nubian Sq. Phase 2",
    "Status": "Not Built",
    "Neighborhood": "Roxbury",
    "Address": "Dudley Square (Malcolm X Blvd, Washington St, Dudley St, Warren St, Harrison Ave)",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "https://drive.google.com/file/d/1letGKSyfYe0DsP2mCBuogvMS-dtbCw9F/view?usp=sharing,\nhttps://drive.google.com/file/d/1wwNG0JI4XU1mTQms85GwAchm-rXz8elY/view?usp=sharing",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "No",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Chesnut Hill",
    "Status": "Not Built",
    "Neighborhood": "",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Columbia La Grange",
    "Status": "Not Built",
    "Neighborhood": "",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Talbot Ave/Colonial Ave",
    "Status": "Not Built",
    "Neighborhood": "",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Canterbury Brook (Three Tributary Areas)",
    "Status": "Study",
    "Neighborhood": "",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "",
    "Maintenance Agreement?": "",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Ruggles Street",
    "Status": "Under Construction",
    "Neighborhood": "Roxbury",
    "Address": "",
    "Asset Type": "Tree plantings, permeable pavers, porous asphalt",
    "Description": "",
    "PIC no.": "2020.0066",
    "Partner Depts.": "",
    "Maintenance Agreement?": "No",
    "Link to Maintenance Agreement": "",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Yes",
    "On PIC List?": ""
  },
  {
    "Asset Name": "Melnea Cass Boulevard",
    "Status": "",
    "Neighborhood": "",
    "Address": "",
    "Asset Type": "",
    "Description": "",
    "PIC no.": "",
    "Partner Depts.": "PWD",
    "Maintenance Agreement?": "Yes",
    "Link to Maintenance Agreement": "https://docs.google.com/document/d/1wCmvCqT8E23JZsSxuWWbVRNxGvPA9V2PPVBSJa_iDk0/edit",
    "Link to Maintenance Checklist": "",
    "Link to Construction Cost + Plans": "",
    "Link to RFQ or Bid Invitation": "",
    "Link to Final Reports": "",
    "Additional Links": "",
    "Included in BWSC Database?": "Maybe",
    "On PIC List?": ""
  }
 ]